### ISSUE TITLE
Migrate deprecated `template_file` 

### ISSUE THREAD

**Issue by vorillaz** [wenzel-felix/terraform-hetzner-nomad-consul-module#29]
Hey there, thanks for this wonderful tool. I am trying to play around with this setup but apparently it fails to run Terraform since `template_file` has no M1 builds, reference can be found [here](https://discuss.hashicorp.com/t/template-v2-2-0-does-not-have-a-package-available-mac-m1/35099)

**Comment by wenzel-felix** [comment]
Hi @vorillaz, thank you for this hint. 
I will check if it can be simply exchanged with https://developer.hashicorp.com/terraform/language/functions/templatefile. THis should be supported for M1.

**Comment by vorillaz** [comment]
Hey, that was quick! Thanks again for this one, I am a total noob playing around with Terraform so I am not sure how I could help. I'll keep an eye on this one.

**Comment by vorillaz** [comment]
@wenzel-felix Btw, can you please send me over an email at info@vorillaz.com, I have a gig that you might be interested. _I'll delete this comment in order to avoid getting spammed._
