### ISSUE TITLE
Error on "terraform apply" in example folder

### ISSUE THREAD

**Issue by mapolu** [wenzel-felix/terraform-hetzner-nomad-consul-module#39]
pwd:  .../terraform-hetzner-nomad-consul-module/examples/simple-setup
cmd: terraform apply
stderr: 
│ Error: Unsupported argument
│ 
│   on main.tf line 13, in module "hetzner-nomad-consul":
│   13:     hetzner_token = var.hetzner_token
│ 
│ An argument named "hetzner_token" is not expected here.
╵
commit: [1e0bda3631ba67878eaa07cc6facb5a9ab01d058](https://github.com/wenzel-felix/terraform-hetzner-nomad-consul-module/commit/1e0bda3631ba67878eaa07cc6facb5a9ab01d058)
also reproduces before #36 

is it supposed to be run that way?

**Comment by wenzel-felix** [comment]
Yes, I just retried it and I can not reproduce this, unfortunately.
The only issue I found is on the outputs of the "simple-setup", that are not yet adjusted to the "non-nomad_token approach"

**Comment by mapolu** [comment]
@wenzel-felix, I've created a devcontainer and verified my environment issue.

**Comment by mapolu** [comment]
@wenzel-felix, the issue was not that simple. I think it may be reproduced by adding cloud backend at the top of simple-setup/main.tf:
```
terraform {
  backend "remote" {
    organization = "<org>"

    workspaces {
      name = "<workspace>"
    }
  }
}
```
During apply stage it should fail to find modules with the error.

FIX: 
Set working directory to "examples/simple-setup" using https://github.com/hashicorp/terraform/issues/22891#issuecomment-737646564 as a guide

**Comment by wenzel-felix** [comment]
@mapolu if you are using the module now in TFC, I'd strongly suggest using it not via a relative path but as shown in the terraform registry (https://registry.terraform.io/modules/wenzel-felix/nomad-consul-module/hetzner/latest):
module "nomad-consul-module" {
  source  = "wenzel-felix/nomad-consul-module/hetzner"
  version = "0.5.0"
  # insert the 1 required variable here
}

This should fix your issue

**Comment by mapolu** [comment]
Sure, I use the tf registry in prod. The relative import issue only appears during development. It was on my way while I was experimenting
